# Generated by Django 3.0.5 on 2020-04-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.TextField(),
        ),
    ]
